### PR TITLE
If multiple possible roots (i.e. functions with no callers) are found…

### LINKED ISSUE #69: SnakeViz draw incorrect sunburst graph
I'm using SnakeViz to profile my **Tornado** based application. Recently I found SnakeViz draw incorrect sunburst graph for some of our profile file. I attached this dsa-engine-worker_manage.out.zip file for you to analyse. 

The problem is SnakeViz only draw the function call of `add_callback`, but not the most important `run_callback`. But I can find the `run_callback` on stats table. So there are something definitely goes wrong.

image
image

[dsa-engine-worker_manage.out.zip](https://github.com/jiffyclub/snakeviz/files/166572/dsa-engine-worker_manage.out.zip)

### PR DESCRIPTION
**Pull request by embray**
…, pick the one with the largest cumtime always.

Fixes #69.

### CODE REVIEW

File: snakeviz/static/snakeviz.js [hunk 1]
```diff
@@ -11,15 +11,16 @@ var sv_find_root = function sv_find_root (stats) {
     var diff = callers.subtract(callees);
     if (diff.size !== 0) {
```
Comment (jiffyclub) [inline snakeviz/static/snakeviz.js]: I wonder if this would have worked if this line was `diff.size === 1` instead? E.g. if the logic should go

```javascript
if (diff.size === 1) {
  return diff.toJS()[0];
} else if (diff.size > 1) {
  return _.max(_.keys(stats), function (s) {
    return stats[s]['stats'][3];
 });
} else {
  throw 'no root found';
}
```

Comment (embray) [inline snakeviz/static/snakeviz.js]: That was my original thought too (about diff.size == 1).  Nevertheless the set difference heuristic between callers and callees is still a useful heuristic for narrowing down the field.  So once you've already done it it's useful to go ahead with the difference set, rather than throwing it out and sorting *all* stats.

Comment (jiffyclub) [inline snakeviz/static/snakeviz.js]: That makes sense.

**Comment by jiffyclub** [comment]
If you've verified this works, :+1:
